# Generated by Django 5.1.6 on 2025-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
