# Generated by Django 5.1.6 on 2025-04-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='total_grade',
            new_name='total_score',
        ),
        migrations.RenameField(
            model_name='studentanswer',
            old_name='grade',
            new_name='score',
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(default='port', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.student')),
            ],
        ),
    ]
