# Generated by Django 5.1.6 on 2025-04-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_rename_total_grade_examresult_total_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentledger',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentledger',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentledger',
            name='teacher_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='studentledger',
            unique_together={('student', 'exam')},
        ),
    ]
