# Generated by Django 5.1.6 on 2025-04-10 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_studentledger_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentledger',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.teacher'),
        ),
        migrations.AlterField(
            model_name='studentledger',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='exams.student'),
        ),
    ]
