# Generated by Django 5.1.6 on 2025-04-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_studentledger_teacher_alter_studentledger_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentledger',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='studentledger',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentledger',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentledger',
            name='teacher_name',
            field=models.CharField(max_length=100),
        ),
    ]
