# Generated by Django 5.1.6 on 2026-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0010_exam_duration_hours_exam_duration_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="Detailed instructions for students before starting",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="description",
            field=models.TextField(
                blank=True, help_text="Brief description of the exam"
            ),
        ),
    ]
