# Generated by Django 5.1.6 on 2026-03-05 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0011_exam_instructions_alter_exam_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="completed_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examresult",
            name="max_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="examresult",
            name="percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="examresult",
            name="time_taken",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
